### ISSUE TITLE
Can this mod be made into a sugar?

### ISSUE THREAD

**Issue by figuerom16** [gnat/surreal#14]
This adds in a small modifier to pick up elementSiblings.
It's been great for picking up single tags at the same level like `<input>` and `<img>`.  Putting some of the scripting outside of a tag like `<td>` is nice for for searching a table without creating a text node.

```javascript
me(selector=null, start=document, warning=true) {
	if (selector == null) return $.sugar(start.currentScript.parentElement) // Just local me() in <script>
	if (selector instanceof Event) return selector.currentTarget ? $.me(selector.currentTarget) : (console.warn(`Surreal: Event currentTarget is null. Please save your element because async will lose it`), null) // Events try currentTarget
	// Goofy mod here.
	if (typeof selector == 'string') {
		if (selector === '<') return $.sugar(start.currentScript.previousElementSibling)
		if (selector === '>') return $.sugar(start.currentScript.nextElementSibling)
		if (isSelector(selector, start, warning)) return $.sugar(start.querySelector(selector)) // String selector.
	}
	if ($.isNodeList(selector)) return $.me(selector[0]) // If we got a list, just take the first element.
	if ($.isNode(selector)) return $.sugar(selector) // Valid element.
	return null // Invalid.
},
```

Is it possible to use the sugar system for this?

**Comment by gnat** [comment]
Interesting. Might add next / previous to core.

**Comment by figuerom16** [comment]
That unfortunately looks like it's going to grab the parent element then next/prev sibling which would dodge grabbing a void element.

What about having me() check if there is a previousElementSibling first if that doesn't exist then use the parent instead?

```javascript
me(selector=null, start=document, warning=true) {
	if (selector == null) { // Just local me() in <script>
		const previous = start.currentScript.previousElementSibling
		if (previous) return $.sugar(previous) // Previous sibling
		return $.sugar(start.currentScript.parentElement) // Parent element
	} 
	if (selector instanceof Event) return selector.currentTarget ? $.me(selector.currentTarget) : (console.warn(`Surreal: Event currentTarget is null. Please save your element because async will lose it`), null) // Events try currentTarget
	if (typeof selector == 'string' && isSelector(selector, start, warning)) return $.sugar(start.querySelector(selector)) // String selector.
	if ($.isNodeList(selector)) return $.me(selector[0]) // If we got a list, just take the first element.
	if ($.isNode(selector)) return $.sugar(selector) // Valid element.
	return null // Invalid.
},
```

That will allow for the capture void elements like input below.

```javascript
<div class="flex">
	<input type="search" placeholder="Search">
	<script>me().on('input', e=>{search_table(me('#tmarkdown'), me(e))})</script>
</div>
```

me() would retrieve input instead of the current behavior of retrieving the div.
moving script below <div class="flex"> would cause it to get that element instead.

**Comment by gazpachoking** [comment]
I was experimenting with some tree traversal over here. https://github.com/gnat/surreal/pull/6 With that system your case would be something like `me.el('input').on(...)`

**Comment by figuerom16** [comment]
@gazpachoking That looks interesting and is beyond what I'm looking for.  My objective is to be as lazy as possible and retrieve previous adjacent element or the parent.  Advanced traversal is beyond me other than using CSS selectors.

I refactored my previous comment for clarity.

**Comment by figuerom16** [comment]
Closing this in favor of PR #17
