### ISSUE TITLE
Payload for custom event

### ISSUE THREAD

**Issue by ilkiri23** [gnat/surreal#16]
It would be great if we could pass payload to the `trigger` function (something like `trigger('click', { value: 42 })`) and get it in the handler
```js
me().on('click', (event) => { 
  console.log(event.detail.value) // 42
})
```
If you agree with that, I can create a PR

**Comment by gnat** [comment]
This is a good idea and I'll add it soon unless you want to make a PR.

**Comment by ilkiri23** [comment]
What do you also think about adding `cancelable: true` option by default?

**Comment by gnat** [comment]
> What do you also think about adding `cancelable: true` option by default?

They already are as far as I know. Check out `halt()`

**Comment by gnat** [comment]
Latest 1.1.6 adds optional event details, and `send()` now aliases `trigger()`.
